---

- name: Install Firefox
  apt:
    pkg: "firefox"
    state: latest
    update_cache: yes
    cache_valid_time: "{{ aptcachetime }}"
  when: ansible_os_family == 'Debian'

- name: Install Firefox
  become: true
  yum:
    name: "firefox"
    state: latest
    update_cache: true
  when: ansible_os_family == 'RedHat'
