---

- name: Install Ruby
  become: true
  apt:
    pkg: "ruby-full"
    state: latest
    update_cache: true
    cache_valid_time: "{{ aptcachetime }}"
  when: ansible_os_family == 'Debian'

- name: Install Ruby
  become: true
  yum:
    name: "ruby"
    state: latest
    update_cache: true
  when: ansible_os_family == 'RedHat'

- name: Install rubymine
  become: true
  snap:
    name: rubymine
    classic: true
