---

- name: Install Thunderbird
  apt:
    pkg: "thunderbird"
    state: latest
    update_cache: yes
    cache_valid_time: "{{ aptcachetime }}"
  when: ansible_os_family == 'Debian'

- name: Install Thunderbird
  become: true
  yum:
    name: "thunderbird"
    state: latest
    update_cache: true
  when: ansible_os_family == 'RedHat'
