---

- name: Install apt-transport-https
  become: true
  apt:
    pkg: "apt-transport-https"
    state: latest
    update_cache: true
    cache_valid_time: "{{ aptcachetime }}"
  when: ansible_os_family == 'Debian'

- name: Add Apt signing key
  become: true
  ansible.builtin.apt_key:
    url: "https://download.sublimetext.com/sublimehq-pub.gpg"
    state: present
  when: ansible_os_family == 'Debian'

- name: Add Yum signing key
  rpm_key:
    key: https://download.sublimetext.com/sublimehq-rpm-pub.gpg
    state: present
  when: ansible_os_family == 'RedHat'

- name: Add repository into sources list
  become: true
  ansible.builtin.apt_repository:
    repo: deb https://download.sublimetext.com/ apt/stable/
    state: present
  when: ansible_os_family == 'Debian'

- name: Add repository into sources list
  become: true
  shell: yum-config-manager --add-repo=https://download.sublimetext.com/rpm/stable/x86_64/sublime-text.repo
  args:
    creates: /etc/yum.repo.d/sublime-text.repo
  when: ansible_os_family == 'RedHat'

- name: Install sublime-merge
  become: true
  apt:
    pkg: "sublime-merge"
    state: latest
    update_cache: true
    cache_valid_time: "{{ aptcachetime }}"
  when: ansible_os_family == 'Debian'

- name: Install sublime-merge
  yum:
    name: "sublime-merge"
    state: latest 
    update_cache: yes
  when: ansible_os_family == 'RedHat'
