---

- name: Install GPG key for SubLimeText
  apt_key:
    url: https://download.sublimetext.com/sublimehq-pub.gpg
    state: present
  when: ansible_os_family == 'Debian'

- name: Install GPG key for SubLimeText
  rpm_key:
    key: https://download.sublimetext.com/sublimehq-rpm-pub.gpg
    state: present
  when: ansible_os_family == 'RedHat'

- name: Add specified repositories into sources list using specified filename
  apt_repository:
    repo: deb {{ item.repo }} {{ item.add }}
    state: present
    filename: "{{ item.file }}"
  with_items:
    - repo: https://download.sublimetext.com/
      add: apt/stable/
      file: sublime
  when: ansible_os_family == 'Debian'

- name: Add specified repositories into sources list using specified filename
  shell: yum-config-manager --add-repo=https://download.sublimetext.com/rpm/stable/x86_64/sublime-text.repo
  args:
    creates: /etc/yum.repo.d/sublime-text.repo
  when: ansible_os_family == 'RedHat'

- name: Install latest sublime package
  apt: 
    pkg: "sublime-text" 
    state: latest 
    update_cache: yes
  when: ansible_os_family == 'Debian'

- name: Install latest sublime package
  yum:
    name: "sublime-text"
    state: latest 
    update_cache: yes
  when: ansible_os_family == 'RedHat'

- name: Prepare sublime directories (1/2)
  file: 
    path: "{{ ansible_env.HOME }}/.config/sublime-text-3/Installed Packages" 
    state: directory 
    owner: "{{ ansible_env.USER }}" 
    group: "{{ ansible_env.USER }}"

- name: Prepare sublime directories (2/2)
  file: 
    path: "{{ ansible_env.HOME }}/.config/sublime-text-3/Packages/User" 
    state: directory 
    owner: "{{ ansible_env.USER }}" 
    group: "{{ ansible_env.USER }}"

- name: Install Package Control for sublime
  get_url: 
    url: "https://packagecontrol.io/Package%20Control.sublime-package" 
    dest: "{{ ansible_env.HOME }}/.config/sublime-text-3/Installed Packages/Package Control.sublime-package"

- name: Copy Package Control settings template for auto-install (REMEMBER TO RUN DOTFILES SYMLINKS FOR REAL AUTO INSTALL PACKAGES)
  copy: 
    src: "Package Control.sublime-settings" 
    dest: "{{ ansible_env.HOME }}/.config/sublime-text-3/Packages/User/Package Control.sublime-settings" 
    owner: "{{ ansible_env.USER }}" 
    group: "{{ ansible_env.USER }}"
