---

- name: Install Git
  become: true
  apt:
    pkg: "git"
    state: latest
    update_cache: true
    cache_valid_time: "{{ aptcachetime }}"
  when: ansible_os_family == 'Debian'

- name: Install Git
  become: true
  yum:
    name: "git"
    state: latest
    update_cache: true
  when: ansible_os_family == 'RedHat'
